# Data Sources Configuration
sources:
  lol_wiki:
    name: "League of Legends Wiki"
    type: "scraper"
    base_url: "https://wiki.leagueoflegends.com"
    endpoints:
      champion_page: "/wiki/{champion}"
    rate_limit_seconds: 1.0
